Fixed LeNet architecture not working
mmasana/FACIL pull request #23
Opened 2022-09-14 14:33 UTC by mmasana

LeNet seemed to not be working properly, I think this is a fix.

@btwardow : can you take a look? maybe this is also what was affecting the tests

2022-09-14 18:44 UTC, btwardow requested changes
Hi Marc! I think that's a good catch :wink: However, I'd leave `LeNet` as a base name and do not change to `lenet`, so then we don't have to modify anything else as the naming is consistent, i.e. in the `network/__init__.py` or test files.

After the change, I run tests. They are still running, but all end being green :clap:

2022-09-14 18:44 UTC, btwardow commented on src/networks/lenet.py
> +def lenet(pretrained=False, **kwargs):
```suggestion
def LeNet(pretrained=False, **kwargs):
```

2022-09-14 18:44 UTC, btwardow commented on src/networks/__init__.py
> +from .lenet import lenet
```suggestion
from .lenet import LeNet
```

2022-09-15 08:55 UTC, mmasana commented
Makes sense to leave the old nomenclature. I had not thought of it so much as just trying to fix it. Nice!

2022-09-15 08:57 UTC, merged